version: '3'
services:
  postgres:
    image: "mdillon/postgis:9.6"
    environment:
      - POSTGRES_DB=pycsw
      - POSTGRES_USER=pycsw
      - POSTGRES_PASSWORD=pycsw
    volumes:
      - db-data:/var/lib/postgresql/data

  pycsw:
    image: urbanai/ecopotential-insitu-metadata-catalogue:latest
    links:
      - postgres
    ports:
      - "8081:8081"

volumes:
  db-data:
    driver: local
